"""auto update

Revision ID: 8d886891c50f
Revises: 41b0524a218e
Create Date: 2026-04-16 12:35:06.295110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d886891c50f'
down_revision: Union[str, Sequence[str], None] = '41b0524a218e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.drop_constraint(op.f('articles_article_code_key'), 'articles', type_='unique')
    op.create_index(op.f('ix_articles_article_code'), 'articles', ['article_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_article_code'), table_name='articles')
    op.create_unique_constraint(op.f('articles_article_code_key'), 'articles', ['article_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###