"""auto update

Revision ID: bf0ddd744750
Revises: e1a0c76307fa
Create Date: 2026-04-16 21:49:40.028168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0ddd744750'
down_revision: Union[str, Sequence[str], None] = 'e1a0c76307fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('template_key', sa.String(), nullable=True),
    sa.Column('article_ids', sa.String(), nullable=True),
    sa.Column('scheduled_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ab_test_id', sa.Integer(), nullable=True),
    sa.Column('ab_variant', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_queue_id'), 'newsletter_queue', ['id'], unique=False)
    op.create_table('newsletter_sent_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('sent_date', sa.String(), nullable=True),
    sa.Column('newsletter_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_sent_history_id'), 'newsletter_sent_history', ['id'], unique=False)
    op.create_table('newsletter_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template_key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('html_content', sa.String(), nullable=True),
    sa.Column('text_content', sa.String(), nullable=True),
    sa.Column('preview_style', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_templates_id'), 'newsletter_templates', ['id'], unique=False)
    op.create_table('subscriber_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('newsletter_frequency', sa.String(), nullable=True),
    sa.Column('template_preference', sa.String(), nullable=True),
    sa.Column('content_format', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_preferences_id'), 'subscriber_preferences', ['id'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('preferred_send_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_id'), 'subscribers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_id'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_subscriber_preferences_id'), table_name='subscriber_preferences')
    op.drop_table('subscriber_preferences')
    op.drop_index(op.f('ix_newsletter_templates_id'), table_name='newsletter_templates')
    op.drop_table('newsletter_templates')
    op.drop_index(op.f('ix_newsletter_sent_history_id'), table_name='newsletter_sent_history')
    op.drop_table('newsletter_sent_history')
    op.drop_index(op.f('ix_newsletter_queue_id'), table_name='newsletter_queue')
    op.drop_table('newsletter_queue')
    # ### end Alembic commands ###